apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-nfs-pvb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual
  volumeName: ssd-nfs-pva
