apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  containers:
  - name: nfs-test-container
    image: nginx
    command: ["/bin/sh"]
    args: ["-c", "mkdir -p /usr/share/nginx/html && nginx -g 'daemon off;'"]
    volumeMounts:
    - name: nfs-storage
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: ssd-nfs-pvb
