apiVersion: v1
kind: Service
metadata:
  name: gttestapi-nodeport
  namespace: demo
spec:
  type: NodePort
  selector:
    app: gttestapi
  ports:
    - name: web
      port: 8080
      targetPort: web
      nodePort: 30002
